<div class="sub_content">
	We've since expanded our life list to 43 sites around the world
	<br/>
	43 Places to See Before You Dies
</div>

<div class="button_list">
	<div class="btn_item">
		<a href="#"><img src="images/earth_icon.jpg">
		<div class="title">
			Sites the world
		</div></a>
	</div>
	<div class="btn_item">
		<a href="#"><img src="images/market_icon.jpg">
		<div class="title">
			Shopping
		</div></a>
	</div>
	<div class="btn_item">
		<a href="#"><img src="images/photo_icon.jpg">
		<div class="title">
			Photography
		</div></a>
	</div>
	<div class="btn_item">
		<a href="#"><img src="images/find_icon.png">
		<div class="title">
			Find the best
		</div></a>
	</div>
	<div class="clearfix"></div>
</div>