<div id="top">
	<div id="sub_top">
		<div id="logo">
			<img src="images/logo.png" />
		</div>
		<div id="main_menu">
			<div id="main_menu_item_active"  class="active">
				<a href="/">Home</a>
			</div>
			<div id="main_menu_item">
				<a href="/">Festivals</a>
			</div>
			<div id="main_menu_item">
				<a href="/">Landscapes</a>
			</div>
			<div id="main_menu_item">
				<a href="/">Guides</a>
			</div>
		</div>
		<div class="clearfix"></div>
	</div>
</div>