<div id="places_grid">
	<div id="sub_places_grid">
		<div class="title">
			Famous places
		</div>
		<div id="sub_places_grid_1">
			<div class="places_item">
				<div id="image"><img src="images/sample_thum.png" />
				</div>
				<div id="title">
					Vung Tau
				</div>
			</div>

			<div class="places_item">
				<div id="image"><img src="images/sample_thum.png" />
				</div>
				<div id="title">
					Vung Tau
				</div>
			</div>

			<div class="places_item">
				<div id="image"><img src="images/sample_thum.png" />
				</div>
				<div id="title">
					Vung Tau
				</div>
			</div>

			<div class="places_item">
				<div id="image"><img src="images/sample_thum.png" />
				</div>
				<div id="title">
					Vung Tau
				</div>
			</div>

			<div class="places_item">
				<div id="image"><img src="images/sample_thum.png" />
				</div>
				<div id="title">
					Vung Tau
				</div>
			</div>

			<div class="places_item">
				<div id="image"><img src="images/sample_thum.png" />
				</div>
				<div id="title">
					Vung Tau
				</div>
			</div>

			<div class="places_item">
				<div id="image"><img src="images/sample_thum.png" />
				</div>
				<div id="title">
					Vung Tau
				</div>
			</div>

			<div class="places_item">
				<div id="image"><img src="images/sample_thum.png" />
				</div>
				<div id="title">
					Vung Tau
				</div>
			</div>

			<div class="places_item">
				<div id="image"><img src="images/sample_thum.png" />
				</div>
				<div id="title">
					Vung Tau
				</div>
			</div>

			<div class="places_item">
				<div id="image"><img src="images/sample_thum.png" />
				</div>
				<div id="title">
					Vung Tau
				</div>
			</div>

			<div class="places_item">
				<div id="image"><img src="images/sample_thum.png" />
				</div>
				<div id="title">
					Vung Tau
				</div>
			</div>

			<div class="places_item">
				<div id="image"><img src="images/sample_thum.png" />
				</div>
				<div id="title">
					Vung Tau
				</div>
			</div>

		</div>

		<div class="clearfix"></div>
	</div>
	<div id="green_ground_bt"></div>
</div>